content:articles:list:
  path: /
  controller: App\Controller\BaseController::list
  methods: GET

content:articles:create:
  path: /
  controller: App\Controller\BaseController::create
  methods: POST

content:articles:view:
  path: /{uuid<[\w\-]{36}>}
  controller: App\Controller\BaseController::view
  methods: GET

content:articles:update:
  path: /{uuid<[\w\-]{36}>}
  controller: App\Controller\BaseController::update
  methods: PUT

content:articles:delete:
  path: /{uuid<[\w\-]{36}>}
  controller: App\Controller\BaseController::delete
  methods: DELETE
